version: "3"
services:
  app:
    image: dm_app_image
    container_name: dm_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URL: postgresql://digmkt:digmkt@db:5432/digmkt
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db

  db:
    container_name: dm_db
    image: postgres:11
    volumes:
      - dm-vol:/var/lib/postgresql/data
      - ./:/workspace
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: digmkt
      POSTGRES_PASSWORD: digmkt
      POSTGRES_DB: digmkt
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  dm-vol:
  cypress-vol:
