{{- $cookieSecret := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print (include "digital-marketplace.fullname" .) }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $cookieSecret = index $secret.data "cookie-secret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "digital-marketplace.fullname" . }}-cookie
  labels: 
{{ include "digital-marketplace.labels" . | indent 4}}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  cookie-secret: {{ $cookieSecret }}
