apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "digital-marketplace.fullname" . }}
  labels:
{{ include "digital-marketplace.labels" . | indent 4}}
spec:
  selector:
    matchLabels:
      app: {{ template "digital-marketplace.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "digital-marketplace.fullname" . }}
    spec:
      containers:
        - name: {{ template "digital-marketplace.fullname" . }}
          image: {{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          env:
          - name: ORIGIN
            value: {{ .Values.route.origin }}
          - name: SERVER_PORT
            value: {{ .Values.app.port | quote }}
          - name: COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                key: cookie-secret
                name: {{ template "digital-marketplace.fullname" . }}-cookie
          - name: DATABASE_SERVICE_NAME
            value: {{ .Values.app.databaseServiceName }}
          - name: POSTGRESQL_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                key: database-service-host
                name: {{ template "digital-marketplace.fullname" . }}-database
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: {{ template "digital-marketplace.fullname" . }}-database
          - name: MAILER_HOST
            value: {{ .Values.app.mailerHost }}
          resources:
            requests:
              memory: {{ .Values.resources.app.requests.memory }}
              cpu: {{ .Values.resources.app.requests.cpu }}
            limits:
              memory: {{ .Values.resources.app.limits.memory }}
              cpu: {{ .Values.resources.app.limits.cpu }}
          ports:
            - containerPort: {{ .Values.app.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.app.port }}
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: "/status"
          #     port: 3000
          #     scheme: HTTP
          #   timeoutSeconds: 10
          #   periodSeconds: 30
          #   successThreshold: 1
          #   failureThreshold: 3
