name: CI
on:
  push:
    branches:
      - feat/proposal-crud-tests
  pull_request:
    types: [opened]
    branches:
      - development
      - master

jobs:
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: |
          echo "${{ secrets.TEST_ENV }}" > .env
      - run: docker compose pull test-db
      - run: yarn
      - run: npm t
  yarn-build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn
      - run: npm run front-end:build
      - run: npm run back-end:build
  pre-commit:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: pip install pre-commit
      - run: pre-commit run --all-files -v
  commitlint:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
