name: e2e
on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    # env:
    #   POSTGRES_URL: "postgresql://digitalmarketplace:digitalmarketplace@localhost:5432/digitalmarketplace"

    #   MAILER_HOST: "foobar"
    #   MAILER_PORT: "321"
    # prevent a hanging process from using all the CI minutes
    timeout-minutes: 10

    services:
      postgres:
        # Docker Hub image
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: digitalmarketplace
          POSTGRES_PASSWORD: digitalmarketplace
          POSTGRES_DB: digitalmarketplace
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name dm_db
          --restart always
        volumes:
          - ${{ github.workspace }}:/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
        # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          PGHOST: localhost
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_ENV: "development"
          POSTGRES_URL: "postgresql://digitalmarketplace:digitalmarketplace@localhost:5432/digitalmarketplace"
          MAILER_GMAIL_USER: "fake@gmail.com"
          MAILER_GMAIL_PASS: "password"
          COOKIE_SECRET: "foobar"
        with:
          build: npm run build
          # start: npm run migrations:latest,npm run start
          start: npm run start
          wait-on: 'http://localhost:3000'
          record: true
